apiVersion: v1
kind: Config
clusters:
- name: "rancher"
  cluster:
    server: "https://ec2-3-215-61-95.compute-1.amazonaws.com/k8s/clusters/c-m-bs7h7v5p"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      GN3TURrMQpOekkxTkRBZUZ3MHlNekV4TWpZd01EQTNNelJhRncwek16RXhNak13TURBM016UmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56QXdPVFUzTWpVME1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRTVtQnRMQ01ZSDhiWAorb0JjRG5nckI4MDJsaEJhOUFVN205NVF6d\
      GluZUh3Mzl6RWt2dzNYdnMwZ0h2aFhuMkFlREMvZVhaYktCeW95CnVBbmJWck8yWTZOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGT\
      0VYaHN6eGQwUTc0MlJmYkNEdmVKcnQzYW1xTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFEVQowd\
      WZiVGJPS1JXU1NQc3VnQ2Mzd0tYMVQxeGtMSmh2WEE0cW02TjY1SUFJZ0lnWnpvMUlneDAxaWgxa\
      WJnQTM2CnZwRlBrWXlUQUhYbW1MUEJsRXNiZnRrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "rancher"
  user:
    token: "kubeconfig-user-cg46f98tlt:xg96rzm2kztz6gfn57bpk5vlftzhbgwdt9kklqzd7gmpvb9jx8c7cr"


contexts:
- name: "rancher"
  context:
    user: "rancher"
    cluster: "rancher"

current-context: "rancher"
